class ProtocolVersion:
    V1 = CASS_PROTOCOL_VERSION_V1
    V2 = CASS_PROTOCOL_VERSION_V2
    V3 = CASS_PROTOCOL_VERSION_V3
    V4 = CASS_PROTOCOL_VERSION_V4
    V5 = CASS_PROTOCOL_VERSION_V5
    DSEV1 = CASS_PROTOCOL_VERSION_DSEV1
    DSEV2 = CASS_PROTOCOL_VERSION_DSEV2


class Consistency:
    ANY = CASS_CONSISTENCY_ANY
    ONE = CASS_CONSISTENCY_ONE
    TWO = CASS_CONSISTENCY_TWO
    THREE = CASS_CONSISTENCY_THREE
    QUORUM = CASS_CONSISTENCY_QUORUM
    ALL = CASS_CONSISTENCY_ALL
    LOCAL_QUORUM = CASS_CONSISTENCY_LOCAL_QUORUM
    EACH_QUORUM = CASS_CONSISTENCY_EACH_QUORUM
    SERIAL = CASS_CONSISTENCY_SERIAL
    LOCAL_SERIAL = CASS_CONSISTENCY_LOCAL_SERIAL
    LOCAL_ONE = CASS_CONSISTENCY_LOCAL_ONE


class SSLVerifyFlags:
    NONE = CASS_SSL_VERIFY_NONE
    PEER_CERT = CASS_SSL_VERIFY_PEER_CERT
    PEER_IDENTITY = CASS_SSL_VERIFY_PEER_CERT
    PEER_IDENTITY_DNS = CASS_SSL_VERIFY_PEER_IDENTITY_DNS
