class Consistency:
    ANY = CASS_CONSISTENCY_ANY
    ONE = CASS_CONSISTENCY_ONE
    TWO = CASS_CONSISTENCY_TWO
    THREE = CASS_CONSISTENCY_THREE
    QUORUM = CASS_CONSISTENCY_QUORUM
    ALL = CASS_CONSISTENCY_ALL
    LOCAL_QUORUM = CASS_CONSISTENCY_LOCAL_QUORUM
    EACH_QUORUM = CASS_CONSISTENCY_EACH_QUORUM
    SERIAL = CASS_CONSISTENCY_SERIAL
    LOCAL_SERIAL = CASS_CONSISTENCY_LOCAL_SERIAL
    LOCAL_ONE = CASS_CONSISTENCY_LOCAL_ONE


