class ProtocolVersion:
    V1 = CASS_PROTOCOL_VERSION_V1
    V2 = CASS_PROTOCOL_VERSION_V2
    V3 = CASS_PROTOCOL_VERSION_V3
    V4 = CASS_PROTOCOL_VERSION_V4
    V5 = CASS_PROTOCOL_VERSION_V5
    DSEV1 = CASS_PROTOCOL_VERSION_DSEV1
    DSEV2 = CASS_PROTOCOL_VERSION_DSEV2


class Consistency:
    ANY = CASS_CONSISTENCY_ANY
    ONE = CASS_CONSISTENCY_ONE
    TWO = CASS_CONSISTENCY_TWO
    THREE = CASS_CONSISTENCY_THREE
    QUORUM = CASS_CONSISTENCY_QUORUM
    ALL = CASS_CONSISTENCY_ALL
    LOCAL_QUORUM = CASS_CONSISTENCY_LOCAL_QUORUM
    EACH_QUORUM = CASS_CONSISTENCY_EACH_QUORUM
    SERIAL = CASS_CONSISTENCY_SERIAL
    LOCAL_SERIAL = CASS_CONSISTENCY_LOCAL_SERIAL
    LOCAL_ONE = CASS_CONSISTENCY_LOCAL_ONE


class SSLVerifyFlags:
    NONE = CASS_SSL_VERIFY_NONE
    PEER_CERT = CASS_SSL_VERIFY_PEER_CERT
    PEER_IDENTITY = CASS_SSL_VERIFY_PEER_CERT
    PEER_IDENTITY_DNS = CASS_SSL_VERIFY_PEER_IDENTITY_DNS


class HostListenerEvent:
    UP = CASS_HOST_LISTENER_EVENT_UP
    DOWN = CASS_HOST_LISTENER_EVENT_DOWN
    ADD = CASS_HOST_LISTENER_EVENT_ADD
    REMOVE = CASS_HOST_LISTENER_EVENT_REMOVE

class ValueType:
    CUSTOM = CASS_VALUE_TYPE_CUSTOM
    ASCII = CASS_VALUE_TYPE_ASCII
    BIGINT = CASS_VALUE_TYPE_BIGINT
    BLOB = CASS_VALUE_TYPE_BLOB
    BOOLEAN = CASS_VALUE_TYPE_BOOLEAN
    COUNTER = CASS_VALUE_TYPE_COUNTER
    DECIMAL = CASS_VALUE_TYPE_DECIMAL
    DOUBLE = CASS_VALUE_TYPE_DOUBLE
    FLOAT = CASS_VALUE_TYPE_FLOAT
    INT = CASS_VALUE_TYPE_INT
    TEXT = CASS_VALUE_TYPE_TEXT
    TIMESTAMP = CASS_VALUE_TYPE_TIMESTAMP
    UUID = CASS_VALUE_TYPE_UUID
    VARCHAR = CASS_VALUE_TYPE_VARCHAR
    VARINT = CASS_VALUE_TYPE_VARINT
    TIMEUUID = CASS_VALUE_TYPE_TIMEUUID
    INET = CASS_VALUE_TYPE_INET
    DATE = CASS_VALUE_TYPE_DATE
    TIME = CASS_VALUE_TYPE_TIME
    SMALL_INT = CASS_VALUE_TYPE_SMALL_INT
    TINY_INT = CASS_VALUE_TYPE_TINY_INT
    DURATION = CASS_VALUE_TYPE_DURATION
    LIST = CASS_VALUE_TYPE_LIST
    MAP = CASS_VALUE_TYPE_MAP
    SET = CASS_VALUE_TYPE_SET
    UDT = CASS_VALUE_TYPE_UDT
    TUPLE = CASS_VALUE_TYPE_TUPLE
