class SSLVerifyFlags:
    NONE = CASS_SSL_VERIFY_NONE
    PEER_CERT = CASS_SSL_VERIFY_PEER_CERT
    PEER_IDENTITY = CASS_SSL_VERIFY_PEER_CERT
    PEER_IDENTITY_DNS = CASS_SSL_VERIFY_PEER_IDENTITY_DNS
