name: CI Linux x86_64

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate manylinux_2_28_x86_64-wheel
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir /tmp/acsylla
          cp -r . /tmp/acsylla
          docker run -v /tmp/acsylla:/io -e "PYTHON_VERSION=${{matrix.python-version}}" quay.io/pypa/manylinux_2_28_x86_64 /io/bin/build_manylinux_2_28_wheel.sh
          mkdir dist
          cp /tmp/acsylla/dist/acsylla-*.whl dist/
      - name: Test dependencies for manylinux_2_28_x86_64-wheel
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install default-jre
          make certs
          docker-compose up -d
          # wait till casssandra server is up, to be improved
          # by checking the readiness of the serivce
          sleep 90
      - name: Test generated manylinux_2_28_x86_64-wheel
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir test_wheel
          cp dist/acsylla-*.whl test_wheel
          pip install virtualenv
          python -m virtualenv env
          source env/bin/activate
          pip install -r requirements-test.txt
          rm -r acsylla
          pip install test_wheel/acsylla-*.whl --upgrade
          make test
