name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install driver dependencies
        run: |
          sudo apt-get install libuv1 libuv1-dev
      - name: Compile Cassandra Driver
        run: |
          make install-driver
      - name: Compile and install dependencies
        run: |
          python -m pip install --upgrade pip
          make compile
          make install-dev
      - name: Docker dependencies
        run: |
          docker-compose up -d
      - name: Test
        run: |
          # wait till casssandra server is up, to be improved
          # by checking the readiness of the serivce
          sleep 30
          docker-compose logs
          make test
