name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Linux driver dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install libuv1 libuv1-dev default-jre
      - name: Install Mac driver dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install cmake libuv openssl
      - name: Compile Cassandra Driver
        run: |
          make install-driver
      - name: Compile and install dependencies
        run: |
          python -m pip install --upgrade pip
          export LDFLAGS="-L/usr/local/opt/openssl/lib"
          export CPPFLAGS="-I/usr/local/opt/openssl/include"
          make compile
          make install-dev
      - name: Lint with flake8
        run: |
          make lint
      - name: Linux Test dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          make certs
          docker-compose up -d
      - name: Mac Test dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install cassandra
          make certs
          cassandra -Dcassandra.config=./conf/cassandra
      - name: Test
        run: |
          # wait till casssandra server is up, to be improved
          # by checking the readiness of the serivce
          sleep 90
          make test
