name: CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Compile Cassandra Driver
      run: |
        cd vendor/cpp-driver
        mkdir build
        cd build
        cmake -D CASS_BUILD_STATIC=ON -D CMAKE_CXX_FLAGS=-fPIC -D CASS_BUILD_SHARED=OFF -D CASS_USE_STATIC_LIBS=ON -D CMAKE_C_FLAGS=-fPIC ..
        make
    - name: Compile and install dependencies
      run: |
        python -m pip install --upgrade pip
        make compile
        make install-dev
    - name: Docker dependencies
      run: |
        docker-compose up -d
    - name: Test
      run: |
        make test
