name: PyPi Linux aarch64 release
on:
  push:
    tags:
      - v*
jobs:
  build:
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    strategy:
      matrix:
        os: [ macos-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Generate manylinux2014_aarch64-wheel
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install docker
          brew install colima
          colima start
          docker run --platform linux/arm64 -v `pwd`:/io -e "PYTHON_VERSION=${{matrix.python-version}}" quay.io/pypa/manylinux2014_aarch64 /io/bin/build_manylinux2014_wheel.sh
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          path: dist/acsylla-*.whl
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.version }}
          path: wheelhouse/
      - name: Display content
        run: ls -R
        working-directory: wheelhouse/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          packages_dir: wheelhouse/
          password: ${{ secrets.PYPY_RELEASE_UPLOAD }}
          repository_url: https://upload.pypi.org/legacy/
